spring:
  flyway:
    locations: classpath:db/migration/common
  datasource:
    username: postgres
    password: P@ssw0rd
    url: jdbc:postgresql://localhost:54501/qyoga
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB