name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./**/test-results/**/*.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_individual_runs: true

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test Reports
          path: |
            ./**/test-results/**/*.xml
            ./**/reports
            ./**/libs